### ISSUE TITLE
[env] 의존성 문제 해결을 위한 이슈

### ISSUE THREAD

**Issue by 4923** [KPMG-Fineapple/fineapple#20]
### JSON 값을 제대로 넘겨받지 못하는 문제
> `SyntaxError: Unexpected end of JSON input`

모델을 직접 돌리는 로직이므로 패키지들을 미리 설치해 둘 필요 있음

### 설치 과정
- 패키지 관리자가 pip, conda 두가지 이므로 둘 다 설치필요
- MacOS 기준

1. conda 설치
```
$ brew install --cask anaconda
```
2. 가상환경 생성
```
# conda create -n <환경명> python=<버전>
# 파이썬 해당 버전을 찾을 수 없다고 할 시 fineapple 까지만 입력 후 실행
$ conda create -n env_fineapple python=3.8
```
3. 가상환경 실행
```
$ conda activate env_fineapple
```
4. 클론 후 패키지 설치
```
$ git clone repo-url
$ pip install -r requirements.txt
$ conda install --file packagelist.txt
```

**Comment by NEM-NE** [comment]
몸도 아플텐데 작성하느라 고생했어 ㅠㅠㅠ 오늘 작업한 거는 최종 배포까지 완료 했으니 내일 중으로 잘 동작하는지 테스트해볼게!

**Comment by 4923** [comment]
## 🐛  `requirements.txt` `packagelist.txt` 설치 시 발생한 문제 정리

### 환경
- macOS Monterey 12.2.1 (M1 chip) 
- python == 3.8
- pip == 22.0.3

### To reproduce
```
$ pip install -r requirements.txt
```

### 1. requirements 설치시 OSError 발생 -> 해결

1. 에러 코드
```
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/System/Volumes/Data/home/conda/feedstock_root/build_artifacts/absl-py_1637088766493/work'
```
2. 원인
pip 20.1 이후로 `freeze >` 명령 사용시 파일 경로가 포함됨

3. 해결
- `pip list --format=freeze > requirements.txt` 
- 위 명령어 이용해 requirements 변경

4. 참고
- 해결방법 및 pip 변경지점 링크: https://stackoverflow.com/questions/62885911/pip-freeze-creates-some-weird-path-instead-of-the-package-version

### 2. 변경된 requirements.txt 로 설치해도 pip list에서 확인할 수 없는 문제 -> 해결

1. 원인
requirements.txt 로 설치하면 중간에 설치 에러 또는 버전 에러 발생할 시 설치가 중단되는데, 너무 상단에서 중지돼서 pip list에 올라올 패키지까지 설치되지 않았음

2. **해결**
오류 무시하고 계속해서 설치하는 명령어 사용
```
# pip install -r requirements.txt 대신
$ cat requirements.txt | xargs -n 1 pip install
```

3. 참고
- 명령어 출처: https://hyunsoft.tistory.com/entry/pip-파일로-설치시-패키지-오류난-부분-skip-하는-방법

### 3. condo package list 설치시 설치 에러 -> 미해결, pip 으로 대신 설치 

1. 에러코드
```
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
```

2. 원인
- conda가 최신 버전이 아닐 시 발생
- conda 채널과 연결이 안 될 경우 발생: conda로 설치하는 방법이 여럿인데 제대로 설치를 안했을떄 발생한다고 함
=> 제대로 설치 한거같은데 왜 문제가 되는지는 모르겠음

3. 해결방법
```
$ conda update --all
```
위 명령어로 업데이트 하면 해결된다고 하는데 업데이트 해도 문제가 여전해서 pip 설치로 설치방법 변경

4. 참고
- https://stackoverflow.com/questions/57518050/conda-install-and-update-do-not-work-also-solving-environment-get-errors

**Comment by NEM-NE** [comment]
결과 공유

![스크린샷 2022-02-18 오전 12 31 16](https://user-images.githubusercontent.com/55152516/154514958-24ded0d3-19db-4124-9911-4a3d4c33d0d6.png)

requirements를 설치하면서 중간중간 에러 발생함

![스크린샷 2022-02-18 오전 12 34 11](https://user-images.githubusercontent.com/55152516/154515275-b67730d4-9b1a-4aeb-b590-54a01bfbf951.png)

**Comment by 4923** [comment]
내쪽에서 설치해야 할건 따로 없는거야? npm 도 깔아둬야 돌아가지 않아?

**Comment by NEM-NE** [comment]
>

**Comment by NEM-NE** [comment]
아니면 지금 줌으로 잠깐 화면 공유하면서 할까?

**Comment by NEM-NE** [comment]
xgboost는 이미 1.5.1 버전 설치되어 잇는데 여기서 로드를 못하고 있어 ㅠ

**Comment by 4923** [comment]
뭐라고 왜이러지 ㅠㅠㅠ 일단 나 npm 설치 완료! 잠시만! 

```
❯ node -v
v17.5.0
❯ npm -v
8.4.1
```

**Comment by 4923** [comment]
### BE
```
❯ cd BE
❯ npm install

added 749 packages, and audited 750 packages in 10s

82 packages are looking for funding
  run `npm fund` for details

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
npm notice
npm notice New minor version of npm available! 8.4.1 -> 8.5.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.5.0
npm notice Run npm install -g npm@8.5.0 to update!
npm notice
```
<img width="1423" alt="스크린샷 2022-02-18 00 45 50" src="https://user-images.githubusercontent.com/60145951/154517590-9f164226-1d5d-4a2b-b2fc-e56133bf592d.png">


## FE
```
/Users/a4923/Desktop/repositories/fineapple
❯ cd FE
❯ npm install

added 607 packages, and audited 608 packages in 11s

103 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

### 로컬 접속 완료
이렇게 접속은 됐고
<img width="1423" alt="스크린샷 2022-02-18 00 48 11" src="https://user-images.githubusercontent.com/60145951/154518047-40235fd2-a130-40d6-8e65-cceb3a6b8458.png">
<img width="1385" alt="스크린샷 2022-02-18 00 49 49" src="https://user-images.githubusercontent.com/60145951/154518338-864e2011-b9f7-4702-873a-16baef77baae.png">

### FE > `npm run dev` 
npm run dev 한 터미널은 이렇게 나와
<img width="1419" alt="스크린샷 2022-02-18 00 50 16" src="https://user-images.githubusercontent.com/60145951/154518500-dbcea03d-925a-4ca5-86a6-ccaceecec7eb.png">

@NEM-NE

**Comment by NEM-NE** [comment]
첫번째 사진 로그 저거 말고 더 없어??

**Comment by 4923** [comment]
잠시 한 5분만! 나 확인하나만 해볼게

**Comment by 4923** [comment]
아... 아니 잠시만 나 다 테스트해봤는데 너 AI/data/private 안에 소비량 데이터 없지않아?
지금 추측되는 원인들이 몇개 있긴 한데 가장 크리티컬한건 그 문제인거같아;  
개인정보라고 초반에 .gitignore 에 추가했어서

네쪽에서 의존성 문제가 해결이 안됐으니 일단 내쪽에서 로컬 테스트 한번 해볼게
오늘 몇시쯤 자? @NEM-NE

**Comment by NEM-NE** [comment]
오늘 2 ~ 3시 전에는 잘 거 같아!

근데 내쪽에서는 안되어도 누나는 데이터를 다 가지고 있으니깐되야하는 거 아니야??

**Comment by 4923** [comment]
아하! 다른 문제 발견
아까 너랑 같은 환경에서 테스트해보려고 클론한 레포에서 실험해본거거든  
포크뜬 레포에서는 작업중인게 있어서 뭔가 꼬일까봐

그런데 데이터가 제대로 안들어간거같아서 다시 테스트 해봤는데 이러네

<img width="1388" alt="스크린샷 2022-02-18 01 12 22" src="https://user-images.githubusercontent.com/60145951/154522693-7c5bf9e8-f5b1-458e-bc30-9f85b0b12a43.png">
<img width="1225" alt="스크린샷 2022-02-18 01 13 23" src="https://user-images.githubusercontent.com/60145951/154522932-b4fde544-eede-4819-a23b-22f148c2c1cb.png">

마찬가지로 파이썬 메인파일 돌릴때는 값이 일단 나오긴 나와
<img width="1227" alt="스크린샷 2022-02-18 01 14 21" src="https://user-images.githubusercontent.com/60145951/154523085-10291e73-9eb6-40c2-aa55-584ad4cfa7f9.png">


근데 AI 폴더 밑일때는 제대로 나오는데 그 밖으로 나오면 폴더 경로를 못찾거든? 이건 모듈화 하다가 문제가 생긴거같아. 해결할 수 있는 문제같고
<img width="1214" alt="스크린샷 2022-02-18 01 15 03" src="https://user-images.githubusercontent.com/60145951/154523313-3b8c959f-d00a-49b4-a433-5c37a3e6f897.png">

일단 저 npm 돌린 부분 에러 뭔지 설명해줄 수 있어?

**Comment by 4923** [comment]
내가 생각하는 원인은 백엔드에서 파이썬 파일 호출하는 과정 문제야

작업 자체를 `fineapple/AI` 기준으로 해서 백엔드에서 파일을 실행할때 경로를 간과한거같네
로그 살펴보면 파일명은 제대로 찾아갔는데 `AI/data` 에서 파일을 불러오는게 아니라 `data/` 에서 불러오거든 현재 내 위치가 `fineapple/` 인데도...? 
두시쯤 잔다고 했으니까 내가 파일들 경로를 한번 수정해보고 그래도 로컬테스트에서 문제 생기면 음... 잠깐 줌 켜고 얘기해보자

**Comment by 4923** [comment]
> 오늘 2 ~ 3시 전에는 잘 거 같아!
> 
> 근데 내쪽에서는 안되어도 누나는 데이터를 다 가지고 있으니깐되야하는 거 아니야??

요거는 위에 설명한대로 데이터 다 가지고있는 내 로컬 작업공간이 아니라 우리 레포 클론한데서 테스트했기 때문에!  
그래서 클론한데에 private 데이터 넣고 테스트해보고 작업중인 내 레포 (데이터 있는!) 에서 테스트 해봤는데 파일 불러오는 문제가 생겼어

전에 코드리뷰할때 `if __name__ == "__main__":` 이거 왜 넣냐고 물어봤었잖아 그거랑 관련된 문제야

**Comment by 4923** [comment]
### 상황 공유
> 경로 다 바꿔봐도 그래프에 변화가 없고 터미널에서만 에러가 찍히길래 더미 데이터로 바꾸고, 임의로 값 변경해봤는데 그래프에 반영이 안 됨

---
### log

<details>
<summary>시도해본 내용 기록</summary>

#### 1. python AI/consumption_main.py 실행시 출력값 문제없이 나오는 것 확인
<img width="1421" alt="스크린샷 2022-02-18 00 59 18" src="https://user-images.githubusercontent.com/60145951/154565856-f20f2b48-45ed-447e-a0c1-671a5c4ab002.png">

#### 2. 그런데도 같은 에러 발생: `Unexpected end of JSON input`
<img width="1789" alt="Unexpected_end_of_JSON_input" src="https://user-images.githubusercontent.com/60145951/154565286-66238bfa-c6d7-4221-880f-38d7add7bdbe.png">

#### 3. `BE/src/consumption/consumption.service.ts` 에서 파일명이 잘못 적힌것 확인 -> 변경
```ts
    # line no.9
    const process = spawnSync('python3', ['../AI/consumption-model.py']);
```
#### 4. 백엔드 파일 만지는것보다 파일명 변경하는게 낫겠어서 `consumption-model.py` 로 파일명 변경
- 원래 파일명 : `consumption_model.py`

#### 5. 이제 이런 에러가 발생함
<img width="1388" alt="스크린샷 2022-02-18 01 12 22" src="https://user-images.githubusercontent.com/60145951/154566128-ef22988f-f4fe-44e0-8d7b-bb645c90f308.png">

#### 6. 영문을 모르겠어서 consumption 값을 원래 더미데이터로 변경했는데 여전히 동일 에러 발생
<img width="1322" alt="스크린샷 2022-02-18 05 37 49" src="https://user-images.githubusercontent.com/60145951/154566721-7cedaf88-30b0-4e19-881f-686300876c41.png">

#### 7. 로드에 문제가 있는건지 확인해보려고 내부 값 하나씩 변경해봤는데 그래프에 변화가 없음 (!?)
시도한 값
- `[100, 100, 100, ... ]`
- `[i for i in range (100, 1000)]` -> [100, 101, 102 ... 999, 1000] 와 같음

#### 8. `BE/src/consumption/consumption.service.ts` 에서 파일 실행 경로가 `../AI/~` 이렇게 되어있어서 데이터 로드 경로를 변경해봄 -> 출력에 문제 없음
- `AI/data/~` -> `../AI/data/~`

|변경 전|변경 후|
|:-:|:-:|
|![전](https://user-images.githubusercontent.com/60145951/154571149-06a19673-918a-4bc7-b460-eae8aa0c02ca.png) | ![후](https://user-images.githubusercontent.com/60145951/154571207-bba0552c-e836-4821-8132-6569af91fb40.png)|

</details>

---
### 에러코드

```
[Nest] 39136  - 2022. 02. 18. 오전 5:28:56 VERBOSE [PowerGenerationController] address: hihi trying to get power generation
[Nest] 39136  - 2022. 02. 18. 오전 5:28:56 VERBOSE [ConsumptionController] address: hihi trying to get consumption
[Nest] 39136  - 2022. 02. 18. 오전 5:28:56   ERROR [ExceptionsHandler] Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ConsumptionService.getConsumption (/Users/a4923/Desktop/repositories/fork_fineapple_ai/BE/src/consumption/consumption.service.ts:10:25)
    at ConsumptionController.getConsumption (/Users/a4923/Desktop/repositories/fork_fineapple_ai/BE/src/consumption/consumption.controller.ts:12:50)
    at /Users/a4923/Desktop/repositories/fork_fineapple_ai/BE/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Users/a4923/Desktop/repositories/fork_fineapple_ai/BE/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /Users/a4923/Desktop/repositories/fork_fineapple_ai/BE/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

### 질문 @NEM-NE 
1. 에러코드에서 `at JSON.parse (<anonymous>)` 의 <annonymous> 부분이 제대로 된 값이 맞을까?
2. 그리고 더미값에 정수만 넣어줬던데 혹시 소수점 자릿수 제한된게 있어? 내 출력값이 대충 `6.12015962600708` 이런식으로 나와서 반올림해줘야할까 싶어서
3. 네 로컬에서 원래 더미로 넣어줬던 값 입력했을때 제대로 작동되고 있는지 + 또 더미값 변화시켰을때 그에따라 결과가 변화하는지 한번 확인부탁해! 

일단 테스트해보라고 모델이 예측한 값 남겨둘게
<details>
<summary>AI/consumption-main.py 실행 결과</summary>

```
{
    "current": 
    [{"date": "2021.1", "value": [17.9, 11.5, 15.1, 14.8, 15.8, 14.5, 16.3, 10.0, 10.6, 16.2, 14.5, 13.4, 11.5, 19.0, 15.0, 12.0, 15.4, 14.1, 16.7, 12.1, 17.3, 15.1, 18.0, 17.3, 11.4, 16.3, 12.1, 12.7, 11.7, 20.7, 20.3, 16.5]}, {"date": "2021.2", "value": [13.5, 14.9, 13.6, 12.4, 14.7, 14.2, 19.6, 15.5, 19.8, 8.9, 5.2, 7.9, 13.2, 17.2, 17.8, 14.6, 13.7, 13.2, 14.7, 13.4, 15.2, 15.5, 14.1, 12.0, 12.9, 13.6, 16.0, 12.7]}, {"date": "2021.3", "value": [18.0, 13.5, 12.7, 11.8, 12.1, 15.3, 12.4, 13.4, 5.2, 8.3, 15.0, 7.6, 16.3, 9.7, 16.5, 18.4, 11.9, 14.9, 15.2, 11.5, 16.9, 13.7, 14.8, 14.8, 10.9, 16.8, 13.8, 12.7, 11.9, 10.8, 13.3]}, {"date": "2021.4", "value": [15.2, 15.8, 16.2, 12.5, 16.7, 11.6, 13.1, 14.0, 16.6, 13.5, 12.6, 13.4, 12.6, 10.8, 15.1, 11.0, 10.9, 14.8, 11.1, 11.1, 10.4, 12.7, 14.1, 9.1, 15.0, 14.7, 9.7, 15.0, 13.7, 16.3]}, {"date": "2021.5", "value": [14.0, 17.1, 11.6, 13.0, 11.2, 13.2, 12.2, 17.7, 11.4, 11.8, 10.8, 15.4, 14.4, 14.6, 20.8, 14.9, 12.5, 11.9, 13.7, 8.6, 16.4, 13.1, 11.6, 14.0, 13.7, 10.8, 16.6, 11.1, 15.4, 9.6, 15.0]}, {"date": "2021.6", "value": [12.2, 11.1, 16.1, 10.3, 9.6, 9.6, 14.2, 13.3, 14.1, 15.9, 17.2, 16.0, 17.6, 17.4, 15.3, 15.4, 12.5, 16.2, 14.4, 17.0, 17.6, 14.5, 14.0, 15.1, 15.1, 15.8, 16.2, 14.2, 13.5, 15.8]}, {"date": "2021.7", "value": [15.9, 18.7, 16.3, 14.5, 14.6, 15.2, 16.4, 13.6, 15.6, 15.0, 20.6, 20.9, 17.7, 19.2, 13.0, 19.1, 24.8, 21.8, 27.1, 18.7, 24.0, 23.3, 21.2, 25.3, 21.8, 24.7, 20.0, 20.5, 19.3, 15.0, 18.9]}, {"date": "2021.8", "value": [18.6, 32.7, 18.3, 24.6, 21.6, 15.5, 21.1, 13.6, 19.2, 15.3, 10.1, 13.8, 17.9, 21.0, 15.9, 17.9, 13.0, 19.5, 14.2, 20.5, 13.9, 12.9, 14.1, 16.2, 13.9, 13.8, 12.9, 14.4, 18.8, 16.6, 12.6]}, {"date": "2021.9", "value": [9.1, 19.5, 14.9, 16.8, 18.4, 20.4, 16.9, 14.4, 12.0, 21.4, 14.1, 20.3, 15.0, 18.7, 13.6, 19.3, 10.0, 7.4, 13.1, 12.7, 20.1, 10.8, 9.7, 14.9, 3.6, 25.6, 11.3, 14.3, 15.3, 12.1]}, {"date": "2021.10", "value": [13.4, 13.8, 15.7, 16.4, 14.7, 16.5, 14.4, 13.7, 17.4, 13.8, 15.1, 18.0, 15.1, 13.8, 17.3, 12.4, 15.6, 16.5, 17.4, 16.3, 13.8, 22.1, 14.7, 13.4, 15.2, 18.4, 16.7, 14.5, 15.9, 16.0, 16.9]}, {"date": "2021.11", "value": [13.2, 17.9, 19.6, 14.6, 14.5, 19.0, 17.0, 21.4, 13.0, 19.2, 12.0, 13.7, 14.1, 15.3, 16.9, 18.2, 18.6, 20.5, 15.5, 13.7, 15.9, 14.4, 15.0, 13.2, 18.1, 14.4, 17.9, 15.5, 17.3, 19.8]}, {"date": "2021.12", "value": [13.4]}], 
    "predict"
    : [{"date": "2022.1", "value": [4.8508477210998535, 5.338593482971191, 3.208631992340088, 3.208631992340088, 3.208631992340088, 8.159523963928223, 5.03131628036499, 5.4700775146484375, 5.356387615203857, 5.990520000457764, 3.208631992340088, 4.622033596038818, 7.0179762840271, 2.8274035453796387, 5.826809406280518, 7.0179762840271, 4.622033596038818, 5.889653205871582, 7.0179762840271, 4.2750444412231445, 5.826809406280518, 5.338593482971191, 7.0179762840271, 5.880728721618652, 5.927676200866699, 5.835733890533447, 5.158657550811768, 5.981595516204834, 5.171510219573975, 5.356387615203857, 5.048951148986816, 5.927676200866699]}, {"date": "2022.2", "value": [5.338593482971191, 5.880728721618652, 5.936600685119629, 5.338593482971191, 5.990520000457764, 5.889653205871582, 5.338593482971191, 5.927676200866699, 5.990520000457764, 5.350121021270752, 5.350121021270752, 5.356387615203857, 5.158657550811768, 5.606781959533691, 5.826809406280518, 5.981595516204834, 5.981595516204834, 5.350121021270752, 7.0179762840271, 5.350121021270752, 5.615706443786621, 5.350121021270752, 5.606781959533691, 5.350121021270752, 7.0179762840271, 5.880728721618652, 5.606781959533691, 7.0179762840271]}, {"date": "2022.3", "value": [7.0179762840271, 5.826809406280518, 5.606781959533691, 7.758697032928467, 6.12015962600708, 5.284578800201416, 5.284578800201416, 7.0179762840271, 5.606781959533691, 5.981595516204834, 5.350121021270752, 5.981595516204834, 5.981595516204834, 5.880728721618652, 5.606781959533691, 5.606781959533691, 7.0179762840271, 5.606781959533691, 7.0179762840271, 5.285438060760498, 5.350121021270752, 5.981595516204834, 5.284578800201416, 5.927676200866699, 6.12015962600708, 5.981595516204834, 7.0179762840271, 5.284578800201416, 5.284578800201416, 7.97271203994751, 7.97271203994751]}, {"date": "2022.4", "value": [5.284578800201416, 8.159523963928223, 7.0179762840271, 5.284578800201416, 5.284578800201416, 5.350121021270752, 6.259929180145264, 7.0179762840271, 5.602623462677002, 6.019292831420898, 7.0179762840271, 5.367158889770508, 5.620521068572998, 5.619661808013916, 5.939034461975098, 7.656301498413086, 7.021239280700684, 6.559200763702393, 7.021239280700684, 7.656301498413086, 5.619661808013916, 6.305368900299072, 6.008334636688232, 5.685203552246094, 7.270394325256348, 5.606781959533691, 5.685203552246094, 7.656301498413086, 7.800683498382568, 7.884151935577393]}, {"date": "2022.5", "value": [7.021239280700684, 5.734760761260986, 6.305368900299072, 7.884151935577393, 7.021239280700684, 7.884151935577393, 7.884151935577393, 7.884151935577393, 7.021239280700684, 6.262166500091553, 1.2253707647323608, 0.978126049041748, 3.1894137859344482, 9.033586502075195, 10.457730293273926, 3.1029183864593506, 7.871805667877197, 6.262166500091553, 8.419929504394531, 5.344559669494629, 1.636714220046997, 23.89624786376953, 5.185783863067627, 9.033586502075195, 5.002988815307617, 1.1211844682693481, 1.636714220046997, 3.8202579021453857, 4.595468997955322, 8.419929504394531, 10.214062690734863]}, {"date": "2022.6", "value": [10.457730293273926, 8.348807334899902, 8.348807334899902, 7.498245716094971, 5.939034461975098, 2.7491490840911865, 7.372790813446045, 7.021239280700684, 6.251577854156494, 7.021239280700684, 8.419929504394531, 7.021239280700684, 7.372790813446045, 5.345028400421143, 7.656301498413086, 6.251577854156494, 7.758697032928467, 5.804969787597656, 7.372790813446045, 7.270394325256348, 7.0179762840271, 7.758697032928467, 5.345028400421143, 5.631412029266357, 7.270394325256348, 2.7491490840911865, 5.826809406280518, 5.024023532867432, 6.019292831420898, 5.367158889770508]}, {"date": "2022.7", "value": [5.367158889770508, 5.685203552246094, 5.620521068572998, 5.620521068572998, 6.008334636688232, 5.367158889770508, 5.432701587677002, 5.36801815032959, 5.880728721618652, 7.0179762840271, 5.981595516204834, 7.0179762840271, 5.606781959533691, 7.0179762840271, 5.606781959533691, 5.880728721618652, 5.367158889770508, 5.367158889770508, 5.432701587677002, 5.356387615203857, 5.36801815032959, 5.880728721618652, 5.36801815032959, 5.606781959533691, 7.0179762840271, 5.432701587677002, 5.880728721618652, 5.615706443786621, 5.606781959533691, 5.356387615203857, 5.889653205871582]}, {"date": "2022.8", "value": [5.936600685119629, 5.981595516204834, 5.880728721618652, 5.606781959533691, 5.367158889770508, 5.927676200866699, 5.889653205871582, 5.432701587677002, 5.981595516204834, 5.826809406280518, 5.880728721618652, 5.889653205871582, 5.826809406280518, 5.981595516204834, 5.835733890533447, 5.615706443786621, 5.880728721618652, 7.0179762840271, 5.835733890533447, 5.285438060760498, 5.606781959533691, 5.826809406280518, 5.606781959533691, 5.927676200866699, 5.880728721618652, 5.606781959533691, 5.615706443786621, 5.285438060760498, 7.0179762840271, 5.835733890533447, 5.826809406280518]}, {"date": "2022.9", "value": [7.0179762840271, 7.0179762840271, 5.835733890533447, 5.285438060760498, 5.835733890533447, 5.285438060760498, 5.284578800201416, 5.284578800201416, 5.285438060760498, 5.284578800201416, 5.615706443786621, 5.285438060760498, 5.284578800201416, 5.284578800201416, 5.285438060760498, 5.990520000457764, 5.889653205871582, 5.615706443786621, 5.350121021270752, 5.284578800201416, 5.889653205871582, 7.0179762840271, 5.350121021270752, 5.835733890533447, 5.826809406280518, 5.159516334533691, 5.835733890533447, 5.889653205871582, 5.158657550811768, 5.285438060760498]}, {"date": "2022.10", "value": [5.889653205871582, 5.350121021270752, 5.615706443786621, 5.285438060760498, 7.0179762840271, 7.0179762840271, 5.338593482971191, 5.158657550811768, 5.4700775146484375, 5.338593482971191, 4.317345142364502, 7.0179762840271, 5.171510219573975, 5.835733890533447, 4.516676425933838, 5.386273384094238, 5.4700775146484375, 5.927676200866699, 7.0179762840271]}, {"date": "2022.11", "value": []}, {"date": "2022.12", "value": []}]
}
```

</details>
