### ISSUE TITLE
Consumption 예측 모델 전달 이슈

### ISSUE THREAD

**Issue by NEM-NE** [KPMG-Fineapple/fineapple#36]
## 발전량 예측 모델

![스크린샷 2022-02-20 오후 11 43 35](https://user-images.githubusercontent.com/55152516/154848216-78d733a4-ae72-4a7b-b193-ec4a4943ed71.png)

발전량 예측 모델은 에러 코드가 발생하는 부분을 삭제하여 해결 (삭제해도 괜찮으면 이대로 반영)

## 소비량 예측 모델

내용 보면 colsample_bytree가 list나 numpy 타입이어야 하는데 현재 코드상으로 아니여서 발생하는 듯

<img width="727" alt="스크린샷 2022-02-20 오후 11 42 49" src="https://user-images.githubusercontent.com/55152516/154848240-f03d2ed7-b233-4a76-8733-53eecddfafa1.png">

**Comment by 4923** [comment]
## 해결

### 발전량 예측 모델
> 발전량 예측 모델은 에러 코드가 발생하는 부분을 삭제하여 해결 (삭제해도 괜찮으면 이대로 반영)

해당 조건문은 테스트할때 필요했던 내용이므로 삭제해도 무관

### 소비량 예측 모델
1. Grid Search CV 진행 중 추출한 하이퍼파라미터 모델에 적용 하단 `train_xgboost 함수 부분 변경함`
```py
# AI/model/consumption/predict_xgboost.py
def train_xgboost(dataset: pd.DataFrame, x_test):
    # training set
    x_train, x_valid, y_train, y_valid = split_dataset(
        dataset, testset_size=0.2, do_shuffle=False)

    # params = {'colsample_bytree': 0.3, 'learning_rate': 0.05,
    #           'max_depth': 3, 'n_estimators': 100}

    # Fitting 5 folds for each of 54 candidates, totalling 270 fits
    # Best parameters: {'colsample_bytree': 0.3, 'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 100}
    # Lowest RMSE:  7.0607787236388955

    # model
    xgb_reg = XGBRegressor(
        colsample_bytree=0.3,
        learning_rate=0.05,
        max_depth=3,
        n_estimators=100,
        eval_set=[(x_train, y_train), (x_valid, y_valid)],
        verbose=False,
        seed=0)

    # Grid Search CV
    # clf = GridSearchCV(estimator=xgb_reg,
    #                    param_grid=params,
    #                    scoring='neg_mean_squared_error',
    #                    verbose=1)
    # clf.fit(x_train, y_train)
    # print("Best parameters:", clf.best_params_)
    # print("Lowest RMSE: ", (-clf.best_score_)**(1/2.0))

    # train
    xgb_reg.fit(
        x_train,
        y_train,
    )

    x_test.drop("일시", axis=1, inplace=True)   # 학습에서 '일시' 사용하지 않으므로 drop
    pred = xgb_reg.predict(x_test)
    pred = pd.Series(pred)
    return xgb_reg, pred
```

2. consumption-main.py 의 visualization 부분 주석처리
```
# AI/consumption-main.py
    print(json.dumps(consumption))

    # --- Visualization ---
    # y_valid = load_2021(BASEDIR_PATH)
    # pred = pd.Series(predict_list)
    # predict_xgboost.visual_xgboost(y_valid, pred, xgbr)
```
## 문제
이렇게 해결해도 로컬에서 같은 에러 발생중

<img width="1241" alt="스크린샷 2022-02-21 14 58 59 1" src="https://user-images.githubusercontent.com/60145951/154897749-035e15f6-b835-40dc-9ca7-96f3a25f0757.png">

<img width="1241" alt="스크린샷 2022-02-21 14 58 24" src="https://user-images.githubusercontent.com/60145951/154897680-b6bb42aa-d422-4b95-b408-0dcbbf653000.png">

**Comment by NEM-NE** [comment]
그냥 python 으로 돌리면 동작은 잘돼??
내가 테스트했을 때는 인공지능 쪽에서 못넘겨주는 거 같던데 ㅠ

**Comment by 4923** [comment]
응 발전량은 제대로 나오고 소비량은 WARNING 뜨는데 그거 고치면 괜찮아 (커밋다시함)

fineapple/BE에서
|발전량|소비량 고치기 전|소비량 고친 후|
|:-|:-|:-|
|`python ../AI/power-generation-main.py`|`python ../AI/consumption-main.py`|`python ../AI/consumption-main.py`|
|![](https://user-images.githubusercontent.com/60145951/154905473-25c53f38-c74b-41f7-8401-472d9dd458b6.png)|![](https://user-images.githubusercontent.com/60145951/154905465-cf189d22-3d75-4390-a636-25210ff3ba23.png)|![](https://user-images.githubusercontent.com/60145951/154905580-fe153e52-228f-4ba2-bf7d-5e6dffa77d67.png)|

소비량은 지난번에 반환값 0으로 나올때 문제 생겼던거랑 비슷한거같은데 🤔 
발전량은 파일명 잘못되어있길래 바꿔놨어 이부분 한번 바꿔보고 생각해보자

```
    # BE/src/power-generation/power-generation.service.ts
    # line no.9
    const process = spawnSync('python3', ['../AI/power-generation-main.py']);
```

<img width="733" alt="스크린샷 2022-02-21 16 14 00" src="https://user-images.githubusercontent.com/60145951/154906370-1d6d744d-0ff6-43c5-83cd-59163c5c8dde.png">
